/** Données de démo — mêmes ids que l’ancien import Firestore. */
export const SAMPLE_TRIPS = [
  {
    id: 'demo_dkr_thies_matin',
    departure_city: 'Gare Routiere de Pompiers (Dakar Plateau) - Dakar',
    destination_city: 'Gare Routiere de Thiès (principale) - Thiès',
    date: '2026-03-22',
    time: '08:00',
    sort_key: '2026-03-22T08:00',
    price: 2500,
    available_seats: 14,
    operator: 'Teranga Bus',
    duration: '1 h',
    booked_seats: [],
  },
  {
    id: 'demo_dkr_thies_soir',
    departure_city: 'Gare Routiere de Petersen - Dakar',
    destination_city: 'Gare Routiere de Thiès (principale) - Thiès',
    date: '2026-03-22',
    time: '17:30',
    sort_key: '2026-03-22T17:30',
    price: 2800,
    available_seats: 10,
    operator: 'DemGaw Express',
    duration: '1 h',
    booked_seats: [],
  },
  {
    id: 'demo_dkr_saintlouis',
    departure_city: 'Gare Routiere de Pompiers (Dakar Plateau) - Dakar',
    destination_city: 'Gare Routiere de Saint-Louis - Saint-Louis',
    date: '2026-03-23',
    time: '07:00',
    sort_key: '2026-03-23T07:00',
    price: 8500,
    available_seats: 6,
    operator: 'Ndiaga Ndiaye',
    duration: '4 h 30',
    booked_seats: [],
  },
  {
    id: 'demo_dkr_kaolack',
    departure_city: 'Gare Routiere de Colobane - Dakar',
    destination_city: 'Gare Routiere de Kaolack (Leone) - Kaolack',
    date: '2026-03-23',
    time: '09:30',
    sort_key: '2026-03-23T09:30',
    price: 6200,
    available_seats: 9,
    operator: 'DemGaw Express',
    duration: '3 h',
    booked_seats: [],
  },
  {
    id: 'demo_thies_dakar',
    departure_city: 'Gare Routiere de Thiès (principale) - Thiès',
    destination_city: 'Gare Routiere de Pompiers (Dakar Plateau) - Dakar',
    date: '2026-03-22',
    time: '18:15',
    sort_key: '2026-03-22T18:15',
    price: 2500,
    available_seats: 16,
    operator: 'Teranga Bus',
    duration: '1 h',
    booked_seats: [],
  },
  {
    id: 'demo_saintlouis_dakar',
    departure_city: 'Gare Routiere de Saint-Louis - Saint-Louis',
    destination_city: 'Gare Routiere de Petersen - Dakar',
    date: '2026-03-24',
    time: '06:00',
    sort_key: '2026-03-24T06:00',
    price: 8000,
    available_seats: 5,
    operator: 'Ndiaga Ndiaye',
    duration: '4 h 30',
    booked_seats: [],
  },
  {
    id: 'demo_kaolack_dakar',
    departure_city: 'Gare Routiere de Kaolack (Leone) - Kaolack',
    destination_city: 'Gare Routiere de Colobane - Dakar',
    date: '2026-03-24',
    time: '10:00',
    sort_key: '2026-03-24T10:00',
    price: 6000,
    available_seats: 11,
    operator: 'DemGaw Express',
    duration: '3 h',
    booked_seats: [],
  },
  {
    id: 'demo_thies_kaolack',
    departure_city: 'Gare Routiere de Thiès (principale) - Thiès',
    destination_city: 'Gare Routiere de Kaolack (Leone) - Kaolack',
    date: '2026-03-25',
    time: '11:00',
    sort_key: '2026-03-25T11:00',
    price: 4500,
    available_seats: 8,
    operator: 'Alhamdoulillah',
    duration: '2 h 15',
    booked_seats: [],
  },
]
